name: Run Tests
on: [ pull_request ]

jobs:
  check-branch:
    name: Check version info and changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - name: Verify version and changelog info
        run: python .github/workflows/CheckBranch.py
  build-python:
    runs-on: ubuntu-latest
    needs: check-branch
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, "3.10", 3.11 ]
    name: Python ${{ matrix.python-version }} build
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run build from branch
        run: python BudgeTeer.py --port=9090 --config="/home/runner/work/_temp/_github_home" --test_run --log-level=DEBUG
  build-vuejs:
    runs-on: ubuntu-latest
    needs: check-branch
    name: Node.js build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
        working-directory: budgeteer/web_interface/vuejs_frontend
      - name: Run build from branch
        run: npm run build
        working-directory: budgeteer/web_interface/vuejs_frontend
